apiVersion: openchoreo.dev/v1alpha1
kind: Resource
metadata:
  name: asdlc-db
  namespace: {{ .Release.Namespace }}
spec:
  owner:
    projectName: asdlc-platform
  type:
    kind: ClusterResourceType
    name: asdlc-postgres
  parameters:
    image: {{ .Values.postgres.image | quote }}
    database: {{ .Values.postgres.auth.database | quote }}
    username: {{ .Values.postgres.auth.username | quote }}
    password: {{ .Values.postgres.auth.password | quote }}
    storage: {{ .Values.postgres.storage | quote }}
