apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: asdlc-db-production
  namespace: {{ .Release.Namespace }}
spec:
  environment: production
  owner:
    projectName: asdlc-platform
    resourceName: asdlc-db
  resourceRelease: asdlc-db-production
