apiVersion: openchoreo.dev/v1alpha1
kind: ComponentRelease
metadata:
  name: asdlc-api-{{ include "ae-platform.tagSuffix" .Values.asdlcApi.image.tag }}
  namespace: {{ .Release.Namespace }}
spec:
  owner:
    projectName: asdlc-platform
    componentName: asdlc-api
  componentType:
    kind: ClusterComponentType
    name: platform-service
    spec:
      {{- include "ae-platform.platformServiceSpec" . | nindent 6 }}
  workload:
    container:
      image: "{{ .Values.asdlcApi.image.repository }}:{{ .Values.asdlcApi.image.tag }}"
    endpoints:
      http:
        type: HTTP
        port: {{ .Values.asdlcApi.port }}
        visibility:
          - project
          - external
