apiVersion: v1
kind: Service
metadata:
  name: agents-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: agents-service
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: wso2-agentic-engineer
spec:
  selector:
    app: agents-service
  ports:
    - port: {{ .Values.agentsService.port }}
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
