// Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/viper"
)

func Init() {
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Fprintln(os.Stderr, "error resolving home dir:", err)
		os.Exit(1)
	}

	cfgDir := filepath.Join(home, ".aep")
	viper.SetConfigName("config")
	viper.SetConfigType("yaml")
	viper.AddConfigPath(cfgDir)
	viper.AddConfigPath(".")

	viper.SetEnvPrefix("AEP")
	viper.AutomaticEnv()

	// Platform install defaults — overridable via ~/.aep/config.yaml.
	// platform.workspaces.access_mode: PVC access mode for the shared git workspaces volume.
	// Use ReadWriteOnce for local k3d (local-path does not support ReadWriteMany).
	// Use ReadWriteMany in production with NFS/EFS/CephFS.
	// Empty string means use the chart default (ReadWriteMany).
	viper.SetDefault("platform.workspaces.access_mode", "")

	// OpenChoreo platform API defaults — overridable via ~/.aep/config.yaml.
	viper.SetDefault("oc.api_url", "http://openchoreo-api.openchoreo-control-plane.svc.cluster.local:8080")

	// Local OpenChoreo org-unit provisioning — overridable via ~/.aep/config.yaml.
	//
	// oc.local_org_provisioning.enabled: LOCAL DEV ONLY. Creates the per-org
	// namespaced ComponentTypes (service/web-application) + api-configuration
	// ClusterTrait that aep-api references — the local stand-in for cloud
	// platform-api ProvisionOrgUnit. NEVER enable in production: there
	// ProvisionOrgUnit creates these per org, and the chart must not.
	// oc.org_namespace: the org's OpenChoreo control-plane namespace where the
	// namespaced ComponentTypes are created (local single-org install → "default").
	viper.SetDefault("oc.local_org_provisioning.enabled", true)
	viper.SetDefault("oc.org_namespace", "default")

	// Coding-agent dispatch + live streaming — overridable via ~/.aep/config.yaml.
	//
	// codingagent.local_stubs.enabled: LOCAL DEV ONLY. Deploys the in-cluster
	// cluster-gateway-proxy stub that aep-api reads coding-agent pod logs + job
	// status through (the live activity feed + JobWatcher). The stub forwards
	// arbitrary Kubernetes API calls with NO auth/allowlist, so it must NEVER be
	// enabled in production. Defaults true here because `aep init` is the local
	// dev install flow; for a prod install set it false in ~/.aep/config.yaml and
	// point cluster_gateway_proxy.url / secret_manager_api.url at the real
	// managed services instead.
	viper.SetDefault("codingagent.local_stubs.enabled", true)
	// Real endpoints for prod (ignored locally when the stub is enabled). Leave
	// secret_manager_api.url empty to keep coding dispatch on the direct K8s Job
	// path (no OpenBao/ESO/sm-api); set it to enable the full proxy dispatch path.
	viper.SetDefault("codingagent.cluster_gateway_proxy.url", "")
	viper.SetDefault("codingagent.secret_manager_api.url", "")

	// GitHub webhook delivery — overridable via ~/.aep/config.yaml.
	//
	// webhook.delivery_url: the URL registered on each repo's webhook. LOCAL →
	// your smee.io channel; PROD → the real public HTTPS URL of aep-api's
	// /api/v1/webhooks/github. The HMAC secret is generated by `aep init` into
	// OpenBao and synced via ESO — it is never set here.
	//
	// webhook.local_smee.enabled: LOCAL DEV ONLY. Deploys an in-cluster
	// smee-client that forwards the smee.io channel into the cluster. smee.io is
	// a third-party public relay, so NEVER enable this in production — set it
	// false and point delivery_url at a real ingress.
	viper.SetDefault("webhook.delivery_url", "")
	viper.SetDefault("webhook.local_smee.enabled", true)

	// Dev mode — local source-driven inner loop (`aep dev ...`). All overridable
	// via ~/.aep/config.yaml. Off by default: dev commands that mutate the cluster
	// (reload/restart/logs) refuse unless dev.enabled is true.
	//
	// dev.project_path: absolute path to a local checkout of the AEP source repo;
	//   `aep dev reload <svc>` builds images from it.
	// dev.k3d_cluster: the k3d cluster name images are imported into
	//   (matches deployments/k3d-local-config.yaml).
	// dev.namespace: the platform release namespace holding the service Deployments.
	// dev.image_prefix: repository prefix for locally-built dev images
	//   (final tag: <prefix>/<service>:dev).
	viper.SetDefault("dev.enabled", false)
	viper.SetDefault("dev.project_path", "")
	viper.SetDefault("dev.k3d_cluster", "openchoreo")
	viper.SetDefault("dev.namespace", "wso2-aep")
	viper.SetDefault("dev.image_prefix", "aep-dev")

	// OpenBao auto-unseal — overridable via ~/.aep/config.yaml.
	// Set openbao.seal.type to awskms, gcpckms, or azurekeyvault for production.
	// Leave empty for Shamir mode (requires manual unsealing after pod restarts).
	viper.SetDefault("openbao.seal.type", "")
	viper.SetDefault("openbao.seal.awskms.region", "")
	viper.SetDefault("openbao.seal.awskms.kms_key_id", "")
	viper.SetDefault("openbao.seal.gcpckms.project", "")
	viper.SetDefault("openbao.seal.gcpckms.region", "global")
	viper.SetDefault("openbao.seal.gcpckms.key_ring", "")
	viper.SetDefault("openbao.seal.gcpckms.crypto_key", "")
	viper.SetDefault("openbao.seal.azurekeyvault.vault_name", "")
	viper.SetDefault("openbao.seal.azurekeyvault.key_name", "")

	// Thunder defaults — all overridable via ~/.aep/config.yaml or AEP_THUNDER_* env vars.
	viper.SetDefault("thunder.namespace", "thunder")
	viper.SetDefault("thunder.url", "http://thunder-service.thunder.svc.cluster.local:8090")
	viper.SetDefault("thunder.config_map", "thunder-config-map")
	viper.SetDefault("thunder.deployment", "thunder-deployment")
	viper.SetDefault("thunder.admin_client_id", "openchoreo-system-app")
	viper.SetDefault("thunder.admin_client_secret", "openchoreo-system-app-secret")
	viper.SetDefault("thunder.public_url", "http://thunder.openchoreo.localhost:8080")

	if err := viper.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			fmt.Fprintln(os.Stderr, "error reading config:", err)
		}
	}
}
