apiVersion: v1
kind: Service
metadata:
  name: asdlc-console
  namespace: {{ .Release.Namespace }}
  labels:
    app: asdlc-console
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: wso2-agentic-engineer
spec:
  selector:
    app: asdlc-console
  ports:
    - port: {{ .Values.console.port }}
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
