apiVersion: v1
kind: Service
metadata:
  name: agents-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: agents-service
  ports:
    - name: http
      port: {{ .Values.agentsService.port }}
      targetPort: {{ .Values.agentsService.port }}
