apiVersion: v1
kind: Service
metadata:
  name: asdlc-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: asdlc-api
  ports:
    - name: http
      port: {{ .Values.asdlcApi.port }}
      targetPort: {{ .Values.asdlcApi.port }}
