// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v6.33.0
// source: admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AnthropicApiKey string                 `protobuf:"bytes,1,opt,name=anthropic_api_key,json=anthropicApiKey,proto3" json:"anthropic_api_key,omitempty"`
	// postgres_password is optional; server auto-generates if empty.
	PostgresPassword string `protobuf:"bytes,2,opt,name=postgres_password,json=postgresPassword,proto3" json:"postgres_password,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetAnthropicApiKey() string {
	if x != nil {
		return x.AnthropicApiKey
	}
	return ""
}

func (x *InitRequest) GetPostgresPassword() string {
	if x != nil {
		return x.PostgresPassword
	}
	return ""
}

type InitEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*InitEvent_Progress
	//	*InitEvent_Complete
	//	*InitEvent_Error
	Payload       isInitEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEvent) Reset() {
	*x = InitEvent{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEvent) ProtoMessage() {}

func (x *InitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEvent.ProtoReflect.Descriptor instead.
func (*InitEvent) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *InitEvent) GetPayload() isInitEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InitEvent) GetProgress() string {
	if x != nil {
		if x, ok := x.Payload.(*InitEvent_Progress); ok {
			return x.Progress
		}
	}
	return ""
}

func (x *InitEvent) GetComplete() *InitComplete {
	if x != nil {
		if x, ok := x.Payload.(*InitEvent_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *InitEvent) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*InitEvent_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isInitEvent_Payload interface {
	isInitEvent_Payload()
}

type InitEvent_Progress struct {
	Progress string `protobuf:"bytes,1,opt,name=progress,proto3,oneof"` // real-time log line
}

type InitEvent_Complete struct {
	Complete *InitComplete `protobuf:"bytes,2,opt,name=complete,proto3,oneof"` // final event — credentials to store
}

type InitEvent_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // terminal error
}

func (*InitEvent_Progress) isInitEvent_Payload() {}

func (*InitEvent_Complete) isInitEvent_Payload() {}

func (*InitEvent_Error) isInitEvent_Payload() {}

type InitComplete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unseal_keys is populated in Shamir mode (no KMS seal configured).
	// Operators must store these — needed to manually unseal after pod restarts.
	UnsealKeys []string `protobuf:"bytes,1,rep,name=unseal_keys,json=unsealKeys,proto3" json:"unseal_keys,omitempty"`
	// recovery_keys is populated in KMS auto-unseal mode.
	// Break-glass emergency use only — not needed for normal restarts.
	RecoveryKeys  []string `protobuf:"bytes,3,rep,name=recovery_keys,json=recoveryKeys,proto3" json:"recovery_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitComplete) Reset() {
	*x = InitComplete{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitComplete) ProtoMessage() {}

func (x *InitComplete) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitComplete.ProtoReflect.Descriptor instead.
func (*InitComplete) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *InitComplete) GetUnsealKeys() []string {
	if x != nil {
		return x.UnsealKeys
	}
	return nil
}

func (x *InitComplete) GetRecoveryKeys() []string {
	if x != nil {
		return x.RecoveryKeys
	}
	return nil
}

type ThunderSetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsoleUrl    string                 `protobuf:"bytes,1,opt,name=console_url,json=consoleUrl,proto3" json:"console_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThunderSetupRequest) Reset() {
	*x = ThunderSetupRequest{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThunderSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThunderSetupRequest) ProtoMessage() {}

func (x *ThunderSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThunderSetupRequest.ProtoReflect.Descriptor instead.
func (*ThunderSetupRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ThunderSetupRequest) GetConsoleUrl() string {
	if x != nil {
		return x.ConsoleUrl
	}
	return ""
}

type ProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEvent) Reset() {
	*x = ProgressEvent{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEvent) ProtoMessage() {}

func (x *ProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEvent.ProtoReflect.Descriptor instead.
func (*ProgressEvent) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\faep.admin.v1\"f\n" +
	"\vInitRequest\x12*\n" +
	"\x11anthropic_api_key\x18\x01 \x01(\tR\x0fanthropicApiKey\x12+\n" +
	"\x11postgres_password\x18\x02 \x01(\tR\x10postgresPassword\"\x86\x01\n" +
	"\tInitEvent\x12\x1c\n" +
	"\bprogress\x18\x01 \x01(\tH\x00R\bprogress\x128\n" +
	"\bcomplete\x18\x02 \x01(\v2\x1a.aep.admin.v1.InitCompleteH\x00R\bcomplete\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\t\n" +
	"\apayload\"Z\n" +
	"\fInitComplete\x12\x1f\n" +
	"\vunseal_keys\x18\x01 \x03(\tR\n" +
	"unsealKeys\x12#\n" +
	"\rrecovery_keys\x18\x03 \x03(\tR\frecoveryKeysJ\x04\b\x02\x10\x03\"6\n" +
	"\x13ThunderSetupRequest\x12\x1f\n" +
	"\vconsole_url\x18\x01 \x01(\tR\n" +
	"consoleUrl\")\n" +
	"\rProgressEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x9a\x01\n" +
	"\bAEPAdmin\x12<\n" +
	"\x04Init\x12\x19.aep.admin.v1.InitRequest\x1a\x17.aep.admin.v1.InitEvent0\x01\x12P\n" +
	"\fThunderSetup\x12!.aep.admin.v1.ThunderSetupRequest\x1a\x1b.aep.admin.v1.ProgressEvent0\x01B)Z'github.com/wso2/aepclt/internal/adminpbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_admin_proto_goTypes = []any{
	(*InitRequest)(nil),         // 0: aep.admin.v1.InitRequest
	(*InitEvent)(nil),           // 1: aep.admin.v1.InitEvent
	(*InitComplete)(nil),        // 2: aep.admin.v1.InitComplete
	(*ThunderSetupRequest)(nil), // 3: aep.admin.v1.ThunderSetupRequest
	(*ProgressEvent)(nil),       // 4: aep.admin.v1.ProgressEvent
}
var file_admin_proto_depIdxs = []int32{
	2, // 0: aep.admin.v1.InitEvent.complete:type_name -> aep.admin.v1.InitComplete
	0, // 1: aep.admin.v1.AEPAdmin.Init:input_type -> aep.admin.v1.InitRequest
	3, // 2: aep.admin.v1.AEPAdmin.ThunderSetup:input_type -> aep.admin.v1.ThunderSetupRequest
	1, // 3: aep.admin.v1.AEPAdmin.Init:output_type -> aep.admin.v1.InitEvent
	4, // 4: aep.admin.v1.AEPAdmin.ThunderSetup:output_type -> aep.admin.v1.ProgressEvent
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_admin_proto_msgTypes[1].OneofWrappers = []any{
		(*InitEvent_Progress)(nil),
		(*InitEvent_Complete)(nil),
		(*InitEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
