// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.0
// source: admin.proto

package adminpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AEPAdmin_Init_FullMethodName         = "/aep.admin.v1.AEPAdmin/Init"
	AEPAdmin_ThunderSetup_FullMethodName = "/aep.admin.v1.AEPAdmin/ThunderSetup"
)

// AEPAdminClient is the client API for AEPAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AEPAdminClient interface {
	// Init provisions OpenBao, seeds secrets, and configures ESO Kubernetes auth.
	// Streams progress events and ends with credentials the operator must store.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InitEvent], error)
	// ThunderSetup registers AEP OAuth clients in Thunder and patches CORS.
	ThunderSetup(ctx context.Context, in *ThunderSetupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error)
}

type aEPAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewAEPAdminClient(cc grpc.ClientConnInterface) AEPAdminClient {
	return &aEPAdminClient{cc}
}

func (c *aEPAdminClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InitEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AEPAdmin_ServiceDesc.Streams[0], AEPAdmin_Init_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InitRequest, InitEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AEPAdmin_InitClient = grpc.ServerStreamingClient[InitEvent]

func (c *aEPAdminClient) ThunderSetup(ctx context.Context, in *ThunderSetupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AEPAdmin_ServiceDesc.Streams[1], AEPAdmin_ThunderSetup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ThunderSetupRequest, ProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AEPAdmin_ThunderSetupClient = grpc.ServerStreamingClient[ProgressEvent]

// AEPAdminServer is the server API for AEPAdmin service.
// All implementations must embed UnimplementedAEPAdminServer
// for forward compatibility.
type AEPAdminServer interface {
	// Init provisions OpenBao, seeds secrets, and configures ESO Kubernetes auth.
	// Streams progress events and ends with credentials the operator must store.
	Init(*InitRequest, grpc.ServerStreamingServer[InitEvent]) error
	// ThunderSetup registers AEP OAuth clients in Thunder and patches CORS.
	ThunderSetup(*ThunderSetupRequest, grpc.ServerStreamingServer[ProgressEvent]) error
	mustEmbedUnimplementedAEPAdminServer()
}

// UnimplementedAEPAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAEPAdminServer struct{}

func (UnimplementedAEPAdminServer) Init(*InitRequest, grpc.ServerStreamingServer[InitEvent]) error {
	return status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedAEPAdminServer) ThunderSetup(*ThunderSetupRequest, grpc.ServerStreamingServer[ProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method ThunderSetup not implemented")
}
func (UnimplementedAEPAdminServer) mustEmbedUnimplementedAEPAdminServer() {}
func (UnimplementedAEPAdminServer) testEmbeddedByValue()                  {}

// UnsafeAEPAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AEPAdminServer will
// result in compilation errors.
type UnsafeAEPAdminServer interface {
	mustEmbedUnimplementedAEPAdminServer()
}

func RegisterAEPAdminServer(s grpc.ServiceRegistrar, srv AEPAdminServer) {
	// If the following call panics, it indicates UnimplementedAEPAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AEPAdmin_ServiceDesc, srv)
}

func _AEPAdmin_Init_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AEPAdminServer).Init(m, &grpc.GenericServerStream[InitRequest, InitEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AEPAdmin_InitServer = grpc.ServerStreamingServer[InitEvent]

func _AEPAdmin_ThunderSetup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ThunderSetupRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AEPAdminServer).ThunderSetup(m, &grpc.GenericServerStream[ThunderSetupRequest, ProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AEPAdmin_ThunderSetupServer = grpc.ServerStreamingServer[ProgressEvent]

// AEPAdmin_ServiceDesc is the grpc.ServiceDesc for AEPAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AEPAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aep.admin.v1.AEPAdmin",
	HandlerType: (*AEPAdminServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Init",
			Handler:       _AEPAdmin_Init_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ThunderSetup",
			Handler:       _AEPAdmin_ThunderSetup_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "admin.proto",
}
