apiVersion: v2
name: wso2-ae-thunder-extension
description: Dedicated Thunder Identity Provider for the WSO2 Agentic Engineer platform.
type: application
version: 0.1.3
appVersion: "0.34.0"
keywords:
  - wso2
  - agentic-engineer
  - identity-provider
maintainers:
  - name: WSO2
    url: https://wso2.com
dependencies:
  - name: thunder
    condition: thunder.enabled
    repository: oci://ghcr.io/asgardeo/helm-charts
    version: "0.34.0"
