// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/asdlc/asdlc-service/clients/openchoreo"
	"github.com/wso2/asdlc/asdlc-service/models"
)

// Ensure, that ComponentClientMock does implement openchoreo.ComponentClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.ComponentClient = &ComponentClientMock{}

// ComponentClientMock is a mock implementation of openchoreo.ComponentClient.
//
//	func TestSomethingThatUsesComponentClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.ComponentClient
//		mockedComponentClient := &ComponentClientMock{
//			CreateComponentFunc: func(ctx context.Context, orgName string, projectName string, req *models.CreateComponentRequest) (*models.Component, error) {
//				panic("mock out the CreateComponent method")
//			},
//			CreateComponentReleaseFunc: func(ctx context.Context, params *models.CreateReleaseParams) error {
//				panic("mock out the CreateComponentRelease method")
//			},
//			CreateReleaseBindingFunc: func(ctx context.Context, orgName string, projectName string, componentName string, environment string, releaseName string) error {
//				panic("mock out the CreateReleaseBinding method")
//			},
//			CreateWorkloadFunc: func(ctx context.Context, orgName string, req *models.CreateWorkloadRequest) error {
//				panic("mock out the CreateWorkload method")
//			},
//			GetComponentFunc: func(ctx context.Context, orgName string, projectName string, componentName string) (*models.Component, error) {
//				panic("mock out the GetComponent method")
//			},
//			GetWorkflowRunFunc: func(ctx context.Context, orgName string, runName string) (*models.WorkflowRun, error) {
//				panic("mock out the GetWorkflowRun method")
//			},
//			ListComponentsFunc: func(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*models.ComponentList, error) {
//				panic("mock out the ListComponents method")
//			},
//			ListDeploymentsFunc: func(ctx context.Context, orgName string, projectName string, componentName string) (*models.DeploymentList, error) {
//				panic("mock out the ListDeployments method")
//			},
//			ListWorkflowRunsFunc: func(ctx context.Context, orgName string, projectName string, componentName string, limit int, cursor string) (*models.WorkflowRunList, error) {
//				panic("mock out the ListWorkflowRuns method")
//			},
//			TriggerBuildFunc: func(ctx context.Context, orgName string, projectName string, componentName string) (*models.WorkflowRun, error) {
//				panic("mock out the TriggerBuild method")
//			},
//			TriggerBuildAtCommitFunc: func(ctx context.Context, orgName string, projectName string, componentName string, commitSHA string) (*models.WorkflowRun, error) {
//				panic("mock out the TriggerBuildAtCommit method")
//			},
//			TriggerCodingAgentFunc: func(ctx context.Context, params openchoreo.CodingAgentParams) (*models.WorkflowRun, error) {
//				panic("mock out the TriggerCodingAgent method")
//			},
//		}
//
//		// use mockedComponentClient in code that requires openchoreo.ComponentClient
//		// and then make assertions.
//
//	}
type ComponentClientMock struct {
	// CreateComponentFunc mocks the CreateComponent method.
	CreateComponentFunc func(ctx context.Context, orgName string, projectName string, req *models.CreateComponentRequest) (*models.Component, error)

	// CreateComponentReleaseFunc mocks the CreateComponentRelease method.
	CreateComponentReleaseFunc func(ctx context.Context, params *models.CreateReleaseParams) error

	// CreateReleaseBindingFunc mocks the CreateReleaseBinding method.
	CreateReleaseBindingFunc func(ctx context.Context, orgName string, projectName string, componentName string, environment string, releaseName string) error

	// CreateWorkloadFunc mocks the CreateWorkload method.
	CreateWorkloadFunc func(ctx context.Context, orgName string, req *models.CreateWorkloadRequest) error

	// GetComponentFunc mocks the GetComponent method.
	GetComponentFunc func(ctx context.Context, orgName string, projectName string, componentName string) (*models.Component, error)

	// GetWorkflowRunFunc mocks the GetWorkflowRun method.
	GetWorkflowRunFunc func(ctx context.Context, orgName string, runName string) (*models.WorkflowRun, error)

	// ListComponentsFunc mocks the ListComponents method.
	ListComponentsFunc func(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*models.ComponentList, error)

	// ListDeploymentsFunc mocks the ListDeployments method.
	ListDeploymentsFunc func(ctx context.Context, orgName string, projectName string, componentName string) (*models.DeploymentList, error)

	// ListWorkflowRunsFunc mocks the ListWorkflowRuns method.
	ListWorkflowRunsFunc func(ctx context.Context, orgName string, projectName string, componentName string, limit int, cursor string) (*models.WorkflowRunList, error)

	// TriggerBuildFunc mocks the TriggerBuild method.
	TriggerBuildFunc func(ctx context.Context, orgName string, projectName string, componentName string) (*models.WorkflowRun, error)

	// TriggerBuildAtCommitFunc mocks the TriggerBuildAtCommit method.
	TriggerBuildAtCommitFunc func(ctx context.Context, orgName string, projectName string, componentName string, commitSHA string) (*models.WorkflowRun, error)

	// TriggerCodingAgentFunc mocks the TriggerCodingAgent method.
	TriggerCodingAgentFunc func(ctx context.Context, params openchoreo.CodingAgentParams) (*models.WorkflowRun, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateComponent holds details about calls to the CreateComponent method.
		CreateComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Req is the req argument value.
			Req *models.CreateComponentRequest
		}
		// CreateComponentRelease holds details about calls to the CreateComponentRelease method.
		CreateComponentRelease []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *models.CreateReleaseParams
		}
		// CreateReleaseBinding holds details about calls to the CreateReleaseBinding method.
		CreateReleaseBinding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Environment is the environment argument value.
			Environment string
			// ReleaseName is the releaseName argument value.
			ReleaseName string
		}
		// CreateWorkload holds details about calls to the CreateWorkload method.
		CreateWorkload []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// Req is the req argument value.
			Req *models.CreateWorkloadRequest
		}
		// GetComponent holds details about calls to the GetComponent method.
		GetComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// GetWorkflowRun holds details about calls to the GetWorkflowRun method.
		GetWorkflowRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// RunName is the runName argument value.
			RunName string
		}
		// ListComponents holds details about calls to the ListComponents method.
		ListComponents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Limit is the limit argument value.
			Limit int
			// Cursor is the cursor argument value.
			Cursor string
		}
		// ListDeployments holds details about calls to the ListDeployments method.
		ListDeployments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// ListWorkflowRuns holds details about calls to the ListWorkflowRuns method.
		ListWorkflowRuns []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Limit is the limit argument value.
			Limit int
			// Cursor is the cursor argument value.
			Cursor string
		}
		// TriggerBuild holds details about calls to the TriggerBuild method.
		TriggerBuild []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// TriggerBuildAtCommit holds details about calls to the TriggerBuildAtCommit method.
		TriggerBuildAtCommit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// CommitSHA is the commitSHA argument value.
			CommitSHA string
		}
		// TriggerCodingAgent holds details about calls to the TriggerCodingAgent method.
		TriggerCodingAgent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params openchoreo.CodingAgentParams
		}
	}
	lockCreateComponent        sync.RWMutex
	lockCreateComponentRelease sync.RWMutex
	lockCreateReleaseBinding   sync.RWMutex
	lockCreateWorkload         sync.RWMutex
	lockGetComponent           sync.RWMutex
	lockGetWorkflowRun         sync.RWMutex
	lockListComponents         sync.RWMutex
	lockListDeployments        sync.RWMutex
	lockListWorkflowRuns       sync.RWMutex
	lockTriggerBuild           sync.RWMutex
	lockTriggerBuildAtCommit   sync.RWMutex
	lockTriggerCodingAgent     sync.RWMutex
}

// CreateComponent calls CreateComponentFunc.
func (mock *ComponentClientMock) CreateComponent(ctx context.Context, orgName string, projectName string, req *models.CreateComponentRequest) (*models.Component, error) {
	if mock.CreateComponentFunc == nil {
		panic("ComponentClientMock.CreateComponentFunc: method is nil but ComponentClient.CreateComponent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Req         *models.CreateComponentRequest
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		Req:         req,
	}
	mock.lockCreateComponent.Lock()
	mock.calls.CreateComponent = append(mock.calls.CreateComponent, callInfo)
	mock.lockCreateComponent.Unlock()
	return mock.CreateComponentFunc(ctx, orgName, projectName, req)
}

// CreateComponentCalls gets all the calls that were made to CreateComponent.
// Check the length with:
//
//	len(mockedComponentClient.CreateComponentCalls())
func (mock *ComponentClientMock) CreateComponentCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	Req         *models.CreateComponentRequest
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Req         *models.CreateComponentRequest
	}
	mock.lockCreateComponent.RLock()
	calls = mock.calls.CreateComponent
	mock.lockCreateComponent.RUnlock()
	return calls
}

// CreateComponentRelease calls CreateComponentReleaseFunc.
func (mock *ComponentClientMock) CreateComponentRelease(ctx context.Context, params *models.CreateReleaseParams) error {
	if mock.CreateComponentReleaseFunc == nil {
		panic("ComponentClientMock.CreateComponentReleaseFunc: method is nil but ComponentClient.CreateComponentRelease was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *models.CreateReleaseParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockCreateComponentRelease.Lock()
	mock.calls.CreateComponentRelease = append(mock.calls.CreateComponentRelease, callInfo)
	mock.lockCreateComponentRelease.Unlock()
	return mock.CreateComponentReleaseFunc(ctx, params)
}

// CreateComponentReleaseCalls gets all the calls that were made to CreateComponentRelease.
// Check the length with:
//
//	len(mockedComponentClient.CreateComponentReleaseCalls())
func (mock *ComponentClientMock) CreateComponentReleaseCalls() []struct {
	Ctx    context.Context
	Params *models.CreateReleaseParams
} {
	var calls []struct {
		Ctx    context.Context
		Params *models.CreateReleaseParams
	}
	mock.lockCreateComponentRelease.RLock()
	calls = mock.calls.CreateComponentRelease
	mock.lockCreateComponentRelease.RUnlock()
	return calls
}

// CreateReleaseBinding calls CreateReleaseBindingFunc.
func (mock *ComponentClientMock) CreateReleaseBinding(ctx context.Context, orgName string, projectName string, componentName string, environment string, releaseName string) error {
	if mock.CreateReleaseBindingFunc == nil {
		panic("ComponentClientMock.CreateReleaseBindingFunc: method is nil but ComponentClient.CreateReleaseBinding was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Environment   string
		ReleaseName   string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Environment:   environment,
		ReleaseName:   releaseName,
	}
	mock.lockCreateReleaseBinding.Lock()
	mock.calls.CreateReleaseBinding = append(mock.calls.CreateReleaseBinding, callInfo)
	mock.lockCreateReleaseBinding.Unlock()
	return mock.CreateReleaseBindingFunc(ctx, orgName, projectName, componentName, environment, releaseName)
}

// CreateReleaseBindingCalls gets all the calls that were made to CreateReleaseBinding.
// Check the length with:
//
//	len(mockedComponentClient.CreateReleaseBindingCalls())
func (mock *ComponentClientMock) CreateReleaseBindingCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Environment   string
	ReleaseName   string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Environment   string
		ReleaseName   string
	}
	mock.lockCreateReleaseBinding.RLock()
	calls = mock.calls.CreateReleaseBinding
	mock.lockCreateReleaseBinding.RUnlock()
	return calls
}

// CreateWorkload calls CreateWorkloadFunc.
func (mock *ComponentClientMock) CreateWorkload(ctx context.Context, orgName string, req *models.CreateWorkloadRequest) error {
	if mock.CreateWorkloadFunc == nil {
		panic("ComponentClientMock.CreateWorkloadFunc: method is nil but ComponentClient.CreateWorkload was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		Req     *models.CreateWorkloadRequest
	}{
		Ctx:     ctx,
		OrgName: orgName,
		Req:     req,
	}
	mock.lockCreateWorkload.Lock()
	mock.calls.CreateWorkload = append(mock.calls.CreateWorkload, callInfo)
	mock.lockCreateWorkload.Unlock()
	return mock.CreateWorkloadFunc(ctx, orgName, req)
}

// CreateWorkloadCalls gets all the calls that were made to CreateWorkload.
// Check the length with:
//
//	len(mockedComponentClient.CreateWorkloadCalls())
func (mock *ComponentClientMock) CreateWorkloadCalls() []struct {
	Ctx     context.Context
	OrgName string
	Req     *models.CreateWorkloadRequest
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		Req     *models.CreateWorkloadRequest
	}
	mock.lockCreateWorkload.RLock()
	calls = mock.calls.CreateWorkload
	mock.lockCreateWorkload.RUnlock()
	return calls
}

// GetComponent calls GetComponentFunc.
func (mock *ComponentClientMock) GetComponent(ctx context.Context, orgName string, projectName string, componentName string) (*models.Component, error) {
	if mock.GetComponentFunc == nil {
		panic("ComponentClientMock.GetComponentFunc: method is nil but ComponentClient.GetComponent was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
	}
	mock.lockGetComponent.Lock()
	mock.calls.GetComponent = append(mock.calls.GetComponent, callInfo)
	mock.lockGetComponent.Unlock()
	return mock.GetComponentFunc(ctx, orgName, projectName, componentName)
}

// GetComponentCalls gets all the calls that were made to GetComponent.
// Check the length with:
//
//	len(mockedComponentClient.GetComponentCalls())
func (mock *ComponentClientMock) GetComponentCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}
	mock.lockGetComponent.RLock()
	calls = mock.calls.GetComponent
	mock.lockGetComponent.RUnlock()
	return calls
}

// GetWorkflowRun calls GetWorkflowRunFunc.
func (mock *ComponentClientMock) GetWorkflowRun(ctx context.Context, orgName string, runName string) (*models.WorkflowRun, error) {
	if mock.GetWorkflowRunFunc == nil {
		panic("ComponentClientMock.GetWorkflowRunFunc: method is nil but ComponentClient.GetWorkflowRun was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		RunName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
		RunName: runName,
	}
	mock.lockGetWorkflowRun.Lock()
	mock.calls.GetWorkflowRun = append(mock.calls.GetWorkflowRun, callInfo)
	mock.lockGetWorkflowRun.Unlock()
	return mock.GetWorkflowRunFunc(ctx, orgName, runName)
}

// GetWorkflowRunCalls gets all the calls that were made to GetWorkflowRun.
// Check the length with:
//
//	len(mockedComponentClient.GetWorkflowRunCalls())
func (mock *ComponentClientMock) GetWorkflowRunCalls() []struct {
	Ctx     context.Context
	OrgName string
	RunName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		RunName string
	}
	mock.lockGetWorkflowRun.RLock()
	calls = mock.calls.GetWorkflowRun
	mock.lockGetWorkflowRun.RUnlock()
	return calls
}

// ListComponents calls ListComponentsFunc.
func (mock *ComponentClientMock) ListComponents(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*models.ComponentList, error) {
	if mock.ListComponentsFunc == nil {
		panic("ComponentClientMock.ListComponentsFunc: method is nil but ComponentClient.ListComponents was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Limit       int
		Cursor      string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		Limit:       limit,
		Cursor:      cursor,
	}
	mock.lockListComponents.Lock()
	mock.calls.ListComponents = append(mock.calls.ListComponents, callInfo)
	mock.lockListComponents.Unlock()
	return mock.ListComponentsFunc(ctx, orgName, projectName, limit, cursor)
}

// ListComponentsCalls gets all the calls that were made to ListComponents.
// Check the length with:
//
//	len(mockedComponentClient.ListComponentsCalls())
func (mock *ComponentClientMock) ListComponentsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	Limit       int
	Cursor      string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Limit       int
		Cursor      string
	}
	mock.lockListComponents.RLock()
	calls = mock.calls.ListComponents
	mock.lockListComponents.RUnlock()
	return calls
}

// ListDeployments calls ListDeploymentsFunc.
func (mock *ComponentClientMock) ListDeployments(ctx context.Context, orgName string, projectName string, componentName string) (*models.DeploymentList, error) {
	if mock.ListDeploymentsFunc == nil {
		panic("ComponentClientMock.ListDeploymentsFunc: method is nil but ComponentClient.ListDeployments was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
	}
	mock.lockListDeployments.Lock()
	mock.calls.ListDeployments = append(mock.calls.ListDeployments, callInfo)
	mock.lockListDeployments.Unlock()
	return mock.ListDeploymentsFunc(ctx, orgName, projectName, componentName)
}

// ListDeploymentsCalls gets all the calls that were made to ListDeployments.
// Check the length with:
//
//	len(mockedComponentClient.ListDeploymentsCalls())
func (mock *ComponentClientMock) ListDeploymentsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}
	mock.lockListDeployments.RLock()
	calls = mock.calls.ListDeployments
	mock.lockListDeployments.RUnlock()
	return calls
}

// ListWorkflowRuns calls ListWorkflowRunsFunc.
func (mock *ComponentClientMock) ListWorkflowRuns(ctx context.Context, orgName string, projectName string, componentName string, limit int, cursor string) (*models.WorkflowRunList, error) {
	if mock.ListWorkflowRunsFunc == nil {
		panic("ComponentClientMock.ListWorkflowRunsFunc: method is nil but ComponentClient.ListWorkflowRuns was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Limit         int
		Cursor        string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Limit:         limit,
		Cursor:        cursor,
	}
	mock.lockListWorkflowRuns.Lock()
	mock.calls.ListWorkflowRuns = append(mock.calls.ListWorkflowRuns, callInfo)
	mock.lockListWorkflowRuns.Unlock()
	return mock.ListWorkflowRunsFunc(ctx, orgName, projectName, componentName, limit, cursor)
}

// ListWorkflowRunsCalls gets all the calls that were made to ListWorkflowRuns.
// Check the length with:
//
//	len(mockedComponentClient.ListWorkflowRunsCalls())
func (mock *ComponentClientMock) ListWorkflowRunsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Limit         int
	Cursor        string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Limit         int
		Cursor        string
	}
	mock.lockListWorkflowRuns.RLock()
	calls = mock.calls.ListWorkflowRuns
	mock.lockListWorkflowRuns.RUnlock()
	return calls
}

// TriggerBuild calls TriggerBuildFunc.
func (mock *ComponentClientMock) TriggerBuild(ctx context.Context, orgName string, projectName string, componentName string) (*models.WorkflowRun, error) {
	if mock.TriggerBuildFunc == nil {
		panic("ComponentClientMock.TriggerBuildFunc: method is nil but ComponentClient.TriggerBuild was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
	}
	mock.lockTriggerBuild.Lock()
	mock.calls.TriggerBuild = append(mock.calls.TriggerBuild, callInfo)
	mock.lockTriggerBuild.Unlock()
	return mock.TriggerBuildFunc(ctx, orgName, projectName, componentName)
}

// TriggerBuildCalls gets all the calls that were made to TriggerBuild.
// Check the length with:
//
//	len(mockedComponentClient.TriggerBuildCalls())
func (mock *ComponentClientMock) TriggerBuildCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}
	mock.lockTriggerBuild.RLock()
	calls = mock.calls.TriggerBuild
	mock.lockTriggerBuild.RUnlock()
	return calls
}

// TriggerBuildAtCommit calls TriggerBuildAtCommitFunc.
func (mock *ComponentClientMock) TriggerBuildAtCommit(ctx context.Context, orgName string, projectName string, componentName string, commitSHA string) (*models.WorkflowRun, error) {
	if mock.TriggerBuildAtCommitFunc == nil {
		panic("ComponentClientMock.TriggerBuildAtCommitFunc: method is nil but ComponentClient.TriggerBuildAtCommit was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		CommitSHA     string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		CommitSHA:     commitSHA,
	}
	mock.lockTriggerBuildAtCommit.Lock()
	mock.calls.TriggerBuildAtCommit = append(mock.calls.TriggerBuildAtCommit, callInfo)
	mock.lockTriggerBuildAtCommit.Unlock()
	return mock.TriggerBuildAtCommitFunc(ctx, orgName, projectName, componentName, commitSHA)
}

// TriggerBuildAtCommitCalls gets all the calls that were made to TriggerBuildAtCommit.
// Check the length with:
//
//	len(mockedComponentClient.TriggerBuildAtCommitCalls())
func (mock *ComponentClientMock) TriggerBuildAtCommitCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	CommitSHA     string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		CommitSHA     string
	}
	mock.lockTriggerBuildAtCommit.RLock()
	calls = mock.calls.TriggerBuildAtCommit
	mock.lockTriggerBuildAtCommit.RUnlock()
	return calls
}

// TriggerCodingAgent calls TriggerCodingAgentFunc.
func (mock *ComponentClientMock) TriggerCodingAgent(ctx context.Context, params openchoreo.CodingAgentParams) (*models.WorkflowRun, error) {
	if mock.TriggerCodingAgentFunc == nil {
		panic("ComponentClientMock.TriggerCodingAgentFunc: method is nil but ComponentClient.TriggerCodingAgent was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params openchoreo.CodingAgentParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockTriggerCodingAgent.Lock()
	mock.calls.TriggerCodingAgent = append(mock.calls.TriggerCodingAgent, callInfo)
	mock.lockTriggerCodingAgent.Unlock()
	return mock.TriggerCodingAgentFunc(ctx, params)
}

// TriggerCodingAgentCalls gets all the calls that were made to TriggerCodingAgent.
// Check the length with:
//
//	len(mockedComponentClient.TriggerCodingAgentCalls())
func (mock *ComponentClientMock) TriggerCodingAgentCalls() []struct {
	Ctx    context.Context
	Params openchoreo.CodingAgentParams
} {
	var calls []struct {
		Ctx    context.Context
		Params openchoreo.CodingAgentParams
	}
	mock.lockTriggerCodingAgent.RLock()
	calls = mock.calls.TriggerCodingAgent
	mock.lockTriggerCodingAgent.RUnlock()
	return calls
}
